export const sizes = {
  medium: {
    width: 230,
    cellSize: 30,
    bigCellSize: 100,
    fontSize: 16,
  },
  large: {
    width: 300,
    cellSize: 40,
    bigCellSize: 150,
    fontSize: 20,
  },
  small: {
    width: 160,
    cellSize: 20,
    bigCellSize: 70,
    fontSize: 12,
  },
};

export const defaultStyles = {
  mainColor: '#2F80ED',
  holidayColor: '#ff0000',
  errorColor: '#ff0000',
  size: sizes.medium,

  INPUT_HEIGHT: 42,
  INPUT_BORDER_RADIUS: 8,
  INPUT_BORDER_COLOR: '#dddddd',
  INPUT_BORDER_SIZE: 1,
  INPUT_HORIZONTAL_PADDINGS: 16,
  INPUT_PADDING: 5,

  FONT_COLOR: '#333333',

  LABEL_FONT_SIZE: 14,
  ERROR_FONT_SIZE: 12,
  ERROR_LABEL_FONT_MARGIN: 2,
  BIG_LABEL_FONT_SIZE: 16,
  BIG_LABEL_MARGIN_BOTTOM: 10,
  DATE_FONT_SIZE: 14,

  FORM_PADDING: 10,

  BUTTON_COLOR: '#aaaaaa',
  BUTTON_FONT_SIZE: 20,
  BUTTON_SIZE: 20,
  BUTTON_MARGIN_LEFT: 10,

  CALENDAR_TOP_OFFSET: 10,
  CALENDAR_BORDER_COLOR: '#E1E1E1',
  CALENDAR_BORDER_RADIUS: 8,
  CALENDAR_BORDER_WIDTH: 1,
  CALENDAR_Z_INDEX: 9999,
  CALENDAR_PADDING: 10,
  CALENDAR_BACKGROUND_COLOR: '#ffffff',
  CALENDAR_MARGIN_BOTTOM: 10,

  CONTROL_PANEL_FONT_WEIGHT: 700,
  CONTROL_PANEL_PADDINGS: 5,

  DAY_CELL_SIZE: 100,

  DOT_SIZE: 20,
  DOT_BOTTOM_OFFSET: 7,

  CELL_BORDER_RADIUS: 8,

  CURRENT_DATE_BACKGROUND_COLOR: '#F1F1F1',
  SELECTED_DATE_COLOR: '#FFFFFF',

  TODO_BORDER_RADIUS: 8,
  TODO_BORDER_COLOR: '#dddddd',
  TODO_BORDER_SIZE: 1,
  TODO_PADDING: 5,
  TODO_HEIGHT: 30,
  TODO_MARGIN_BOTTOM: 10,
  TODO_FONT_SIZE: 12,
  TODO_BUTTONS_CONTAINER_WIDTH: 35,
  TODO_BUTTON_SIZE: 14,
  TODO_BUTTON_COLOR: '#aaaaaa',
  TODO_BUTTON_BORDER_SIZE: 1,
  TODO_DATE_SIZE: 14,
  TODO_BACKGROUND_COLOR: '#ffffff',
  TODO_Z_INDEX: 999999,
  TODO_PADDINGS: 10,

  MARK_POSITION_LEFT: 5,
  MARK_POSITION_BOTTOM: 3,
  MARK_WIDTH: 2,
  MARK_SIZE_LEFT: 4,
  MARK_SIZE_RIGHT: 11,
};
